# Generated by Django 2.1.7 on 2019-07-10 14:17

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CycleImg',
            fields=[
                ('img_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='img/%Y%m%d')),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DecompositionFile',
            fields=[
                ('file', models.FileField(upload_to='decomposition/%Y%m%d')),
                ('file_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DecompReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_file', models.FileField(upload_to='reference')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('download_file', models.FileField(upload_to='download/%Y%m%d')),
                ('download_file_hash_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='InputParams',
            fields=[
                ('GC', models.CharField(max_length=255)),
                ('EA', models.FloatField(validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)])),
                ('H', models.FloatField(validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)])),
                ('H2O', models.FloatField(validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)])),
                ('PI', models.FloatField(validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)])),
                ('NH4', models.FloatField(validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)])),
                ('NO3', models.FloatField(validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)])),
                ('SO4', models.FloatField(validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)])),
                ('O2', models.FloatField(validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)])),
                ('input_hash_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('upload_file_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('file', models.FileField(upload_to='upload/%Y%m%d')),
                ('hash_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2019, 7, 10, 14, 17, 40, 116805, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='inputparams',
            name='upload_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biology.UploadFile'),
        ),
        migrations.AddField(
            model_name='downloadfile',
            name='input_params',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biology.InputParams'),
        ),
        migrations.AddField(
            model_name='cycleimg',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biology.DecompositionFile'),
        ),
    ]
