# Generated by Django 2.1.7 on 2019-07-25 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('biology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecompositionScripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scripts', models.FileField(upload_to='scripts')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 25, 11, 2, 37, 764847, tzinfo=utc)),
        ),
    ]
