# Generated by Django 2.1.7 on 2019-08-06 16:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('biology', '0002_auto_20190725_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DecompositionScripts',
        ),
        migrations.DeleteModel(
            name='DecompReference',
        ),
        migrations.AlterModelOptions(
            name='decompositionfile',
            options={'verbose_name_plural': 'Uploaded_Decomposition_File'},
        ),
        migrations.AlterModelOptions(
            name='inputparams',
            options={'verbose_name_plural': 'FBA_Results'},
        ),
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'verbose_name_plural': 'Uploaded_Model'},
        ),
        migrations.AlterField(
            model_name='inputparams',
            name='EA',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inputparams',
            name='H',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inputparams',
            name='H2O',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inputparams',
            name='NH4',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inputparams',
            name='NO3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inputparams',
            name='O2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inputparams',
            name='PI',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inputparams',
            name='SO4',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 6, 16, 33, 12, 447296, tzinfo=utc)),
        ),
    ]
